ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns=[
    path('',views.product_list, name='product_list'),
    path('home', views.home, name='home'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from cart.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cart.urls')),
    path('register/',register_page, name='register_page'),
    path('login/',login_page, name='login_page'),
    path('logout/',signout,name='signout')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Product(models.Model):
    name=models.CharField(max_length=100)
    description=models.TextField(null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    image=models.ImageField(upload_to='product/')

    def __str__(self):
        return self.name
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=0)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity}  {self.product.name}'
    

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from cart.models import Product, CartItem
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages

def product_list(request):
    products=Product.objects.all()
    return render(request,'cart/index.html',{'products':products})
def view_cart(request):
    cart_items=CartItem.objects.filter(user=request.user)
    total_price=sum(item.product.price*item.quantity for item in cart_items)
    return render(request,'cart/cart.html',{'cart_items':cart_items,'total_price':total_price})
def add_to_cart(request, product_id):
    product=Product.objects.get(id=product_id)
    cart_item, created=CartItem.objects.get_or_create(product=product,user=request.user)
    cart_item.quantity+=1
    cart_item.save()
    return redirect('cart:view_cart')
def remove_from_cart(request, item_id):
    cart_item=CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('cart:view_cart')
def home(request):
    return HttpResponse('Hello, World!')
def login_page(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        
        if not User.objects.filter(username=username).exists():
            messages.error(request,'Invalid Username')
            return redirect('/login/')
        user=authenticate(username=username, password=password)
        print(user)

        if user is None:
            messages.error(request,'Invalid Password')
            return redirect('/login/')
        else:
            login(request,user)
            return redirect('cart:product_list')
    return render(request,'cart/login.html')
    
def register_page(request):
    if request.method=="POST":
        first_name=request.POST.get('first_name')
        last_name=request.POST.get('last_name')
        username=request.POST.get('username')
        password=request.POST.get('passsword')

        user=User.objects.filter(username=username)

        if user.exists():
            messages.info(request,'Username already taken!')
            return redirect('/register/')
        user=User.objects.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username
        )

        user.set_password(password)
        user.save()

        messages.info(request,"Account created Successfully!")
        return redirect('/register/')
    return render(request,"cart/register.html")
def signout(request):
    logout(request)
    return redirect('/login')

ecommerce/templates/cart/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .product-list{
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            list-style: none;
            padding: 0;
        }
        .product-item{
            flex: 1;
            margin: 10px;
            border: 1px solid #ccc;
            padding: 10px;
            text-align: center;
        }
        .buy-now-button{
            display: block;
            margin-top: 10px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            padding: 5px 10px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <h1>Your Shopping Cart</h1>
    <div class="product-list">
        {%for item in cart_items %}
        <div class="product-item">
            <img src="{{item.product.image.url}}" alt="{{item.product.name}}" width="200" height="150">
            <p>{{item.product.name}}  ({{item.quantity}})</p>
            <p>Price: Rs{{item.product.price}}</p>
            <a href="{% url 'cart:remove_from_cart' item.id%}">Remove</a>
        </div>
        {%empty%}
        <p>Your cart is empty.</p>
        {%endfor%}
    </div>
        <p>Total Price: Rs{{total_price}}</p>
        <a href="{%url 'cart:product_list'%}">Continue Shopping</a>
</body>
</html>

ecommerce/templates/cart/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .product-list{
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            list-style: none;
            padding: 0;
        }
        .product-item{
            flex: 1;
            max-width: 30%;
            margin: 10px;
            border: 1px solid #2c1414;
            padding: 10px;
            text-align: center;
        }
        .buy-now-button{
            display: block;
            margin-top: 10px;
            background-color: #007bff;
            color:#fff;
            text-decoration: none;
            padding: 5px 10px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <h1>Product Catalog</h1>
    <ul class="product-list">
        {%for product in products %}
        <li class="product-item">
            <img src="{{product.image.url}}" alt="{{product.name}}" width="200" height="150">
            <h2>{{product.name}}</h2>
            <p>{{product.description}}</p>
            <p>Price: Rs {{product.price}}</p>
            <a href="#" class="buy-now-button">Buy Now</a>
            <a class="buy-now-button" href="{% url 'cart:add_to_cart' product.id %}">Add to Cart</a>

        </li>
        {% endfor %}
    </ul>
</body>
</html>

ecommerce/templates/cart/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color: rgb(245, 248, 251);
        }
        .container{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100vh;
            border-radius: 2px;
        }
        .user-info h1{
            text-align: center;
            color: green;
            font-weight:800;
            
        }
        .inputbox{
            margin: 15px;
        }
        .inputbox input{
            margin-top: 10px;
            width: 100%;
            height: 25px;
            border-radius:4px;
            
         }
         .inputbox input:hover{
            border: 2px solid rgb(188, 209, 246);
            background-color: rgb(175, 205, 240);
            
            
         }
           
        .user-info{
            width: 440px;
            height: 380px;
            background-color: white;
            padding: 10px;
            box-shadow: 2px 2px 20px rgb(190, 187, 187);

        }
        .submit-btn input{
            width: 100%;
            background-color: blue;
            color: white;
            height: 25px;
            border-radius: 4px;
            cursor: pointer;
        }
        .container a{
            text-decoration: none;
        }
        .msg{
            background-color: rgb(69, 40, 137);
            width: 100%;
            height: 30px;
            text-align: justify;
            display: flex;
            align-items: center;
            padding-left: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <form action="/login/" method="post">
            {%csrf_token%}
            <div class="user-info">
                <h1>Ecommerce</h1>
                <h2>Login</h2><hr>
                {% if messages %}
                    {% for message in messages %}                        
                            <div class="msg">
                                {{ message }}
                            </div>                      
                    {% endfor %} <!-- Close the for loop -->
                {% endif %} <!-- Close the outer if block -->
                <div class="inputbox">
                    <label for="">Username</label><br>
                    <input type="email"  name="username" required>
                </div>
                <div class="inputbox">
                    <label for="">Password</label><br>
                    <input type="password"  name="password" required>
                </div>
                <p>Don't have an account <a href="/register/">Register</a></p>
                <div class="submit-btn">
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
    
</body>
</html>

ecommerce/templates/cart/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color: rgb(245, 248, 251);
        }
        .container{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100vh;
            border-radius: 2px;
        }
        .form-heading{
            display: flex;
            justify-content: center;
            color: green;
            font-size: 20px;
        }
        .inputbox{
            margin: 15px;
        }
        .inputbox input{
            margin-top: 10px;
            width: 100%;
            height: 25px;
            border-radius:4px;
         }
         .inputbox input:hover{
            border: 2px solid rgb(62, 130, 247);
            
         }
           
        .user-info{
            width: 400px;
            height: 530px;
            background-color: white;
            padding: 10px;
            box-shadow: 2px 2px 20px rgb(190, 187, 187);

        }
        .submit-btn input{
            width: 100%;
            background-color: blue;
            color: white;
            height: 25px;
            border-radius: 4px;
            cursor: pointer;
        }
        .container a{
            text-decoration: none;
        }
        .msg{
            background-color: rgb(175, 203, 248);
            height: 33px;
            border-radius: 4px;
            display: flex;        
            align-items: center;
            padding-left: 16px;
            margin: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        <form action="/register/" method="POST">
            {%csrf_token%}
            <div class="user-info">
                <div class="form-heading"><h2>Ecommerce</h2></div>
                <h2>Register</h2><hr>
                {% if messages %}
                    {% for message in messages %}                        
                            <div class="msg">
                                {{ message }}
                            </div>                      
                    {% endfor %} <!-- Close the for loop -->
                {% endif %} <!-- Close the outer if block -->
                <div class="inputbox">
                    <label for="">First name</label><br>
                    <input type="text" placeholder="Enter First name" name="first_name">
                </div>
                <div class="inputbox">
                    <label for="">Last name</label><br>
                    <input type="text" placeholder="Enter Last name" name="last_name" required>
                </div>
                <div class="inputbox">
                    <label for="">Username</label><br>
                    <input type="email" placeholder="Enter email" name="username" required>
                </div>
                <div class="inputbox">
                    <label for="">Password</label><br>
                    <input type="password" placeholder="Password" name="password" required>
                </div>
                <p>Already have an account <a href="/login/">Login</a></p>
                <div class="submit-btn">
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
    
</body>
</html>